credentials:
  usernames:
    aluno:
      email: alunoUFTM@gmail.com
      name: Aluno
      password: aluno2024
    professor:
      email: profUFTM@gmail.com
      name: Professor
      password: professor2024
cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - direcao@gmail.com